#!/usr/bin/env python3
"""Check the repo surface for obvious private or provenance leftovers."""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path


SCAN_EXTENSIONS = {".md", ".json", ".jsonl", ".py", ".txt", ".yaml", ".yml"}
SKIP_DIRS = {".git", ".pytest_cache", "__pycache__"}


@dataclass(frozen=True)
class PatternCheck:
    label: str
    pattern: re.Pattern[str]


CHECKS = (
    PatternCheck("windows absolute path", re.compile(r"\b[A-Za-z]:[\\/]")),
    PatternCheck("cloud sync path", re.compile("One" + "Drive", re.IGNORECASE)),
    PatternCheck("unix home path", re.compile(r"/(?:Users|home)/[A-Za-z0-9._-]+/")),
    PatternCheck("secret-looking api key", re.compile(r"s" r"k-[A-Za-z0-9_-]{20,}")),
    PatternCheck(
        "secret-looking aws access key",
        re.compile(r"\b(?:AKIA|ASIA)[A-Z0-9]{16}\b"),
    ),
    PatternCheck(
        "secret-looking github token",
        re.compile(r"\b(?:ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9_]{20,}"),
    ),
    PatternCheck(
        "secret-looking github fine-grained token",
        re.compile(r"\bgithub_pat_[A-Za-z0-9_]{20,}"),
    ),
    PatternCheck(
        "private key block",
        re.compile(r"BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY"),
    ),
    PatternCheck(
        "chatgpt provenance marker",
        re.compile(
            "|".join(
                re.escape(value)
                for value in (
                    "generated by " + "ChatGPT",
                    "created by " + "ChatGPT",
                    "written by " + "ChatGPT",
                )
            ),
            re.IGNORECASE,
        ),
    ),
    PatternCheck(
        "ai provenance marker",
        re.compile(
            "|".join(
                re.escape(value)
                for value in (
                    "generated by " + "AI",
                    "AI" + "-generated",
                    "AI" + " generated",
                    "created by " + "AI",
                )
            ),
            re.IGNORECASE,
        ),
    ),
    PatternCheck(
        "internal agent marker",
        re.compile(
            "|".join(
                re.escape(value)
                for value in (
                    "Codex" + " internal",
                    "daily" + "-agent",
                )
            ),
            re.IGNORECASE,
        ),
    ),
)


def should_scan(path: Path, repo_root: Path) -> bool:
    rel_parts = path.relative_to(repo_root).parts
    return path.suffix in SCAN_EXTENSIONS and not any(part in SKIP_DIRS for part in rel_parts)


def clean_snippet(line: str) -> str:
    return re.sub(r"\s+", " ", line).strip()[:160]


def main() -> int:
    repo_root = Path(__file__).resolve().parents[1]
    findings: list[str] = []

    for path in sorted(repo_root.rglob("*")):
        if not path.is_file() or not should_scan(path, repo_root):
            continue

        rel_path = path.relative_to(repo_root).as_posix()
        text = path.read_text(encoding="utf-8")
        for line_number, line in enumerate(text.splitlines(), start=1):
            for check in CHECKS:
                if check.pattern.search(line):
                    snippet = clean_snippet(line)
                    findings.append(f"{rel_path}:{line_number}: {check.label}: {snippet}")

    if findings:
        for finding in findings:
            print(f"error: {finding}", file=sys.stderr)
        return 1

    print("ok: public surface check passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
